### ISSUE TITLE
Criar usuário (Coord. da Entidade) no Firebase Authentication

### ISSUE THREAD

**Issue by edoura** [Ongbook/mvp#21]
- [x] Criar usuário no Firebase **Authentication** e vincular o usuário coordenador à Entidade a ser cadastrada;
- [x] ➡ substituir Input **area-de-atuação** por select com lista hard-code - ```Atividade do Passo 2``` - #9
- [x] ➡ Validações nos inputs e-mail e senha - ```Atividade do Passo 3```- #10;

**Comment by edoura** [comment]
```html
<select name="area-de-atuacao">
          <option value="Idosos">Idosos</option>
          <option value="Crianças">Crianças</option>
          <option value="Animais">Animais</option>
          <option value="Saúde">Saúde</option>
          <option value="Educação">Educação</option>
          <option value="Apoio a Mulheres">Apoio a Mulheres</option>
          <option value="Meio Ambiente">Meio Ambiente</option>
          <option value="Combate a Pobreza">Combate a Pobreza</option>
          <option value="Esporte">Esporte</option>
          <option value="Inovação Tecnológica">Inovação Tecnológica</option>
          <option value="Cultura">Cultura</option>
          <option value="Dependentes Químicos">Dependentes Químicos</option>
          <option value="Finanças">Finanças</option>
          <option value="Doação de Órgãos">Doação de Órgãos</option>
          <option value="Outros">Outros</option>
</select>
```

@JordanPena, o combinado :+1: 
Caso perceba que possa incrementar alguma área ou remover alguma, fique á vontade irmão.
tamo junto! :handshake:

**Comment by edoura** [comment]
> ```
> <select name="area-de-atuacao">
>           <option value="Idosos">Idosos</option>
>           <option value="Crianças">Crianças</option>
>           <option value="Animais">Animais</option>
>           <option value="Saúde">Saúde</option>
>           <option value="Educação">Educação</option>
>           <option value="Apoio a Mulheres">Apoio a Mulheres</option>
>           <option value="Meio Ambiente">Meio Ambiente</option>
>           <option value="Combate a Pobreza">Combate a Pobreza</option>
>           <option value="Esporte">Esporte</option>
>           <option value="Inovação Tecnológica">Inovação Tecnológica</option>
>           <option value="Cultura">Cultura</option>
>           <option value="Dependentes Químicos">Dependentes Químicos</option>
>           <option value="Finanças">Finanças</option>
>           <option value="Doação de Órgãos">Doação de Órgãos</option>
>           <option value="Outros">Outros</option>
> </select>
> ```
> 
> @JordanPena, o combinado 
> Caso perceba que possa incrementar alguma área ou remover alguma, fique á vontade irmão.
> tamo junto! 
> Se atente aos **tabs** da vida ai nesse codéégo

@JordanPena, estive fazendo algumas edições no passo 2 do cadastro e aproveitei e coloquei esse `<select></select>`, beleza? 
Lembre de atualizar o projeto local ai para evoluir com as outras tasks :+1:

**Comment by JordanPena** [comment]
@edoura Beleza!!

**Comment by edoura** [comment]
Pow mano @JordanPena :clap:  :clap:  :clap:  :clap:  Parabéns! Está ficando show o trabalho!
Obrigado  :pray:
